spring:
  application:
    name: api-checkout
  data:
    mongodb:
      host: "${MONGODB_HOST:localhost}"
      port: "${MONGODB_PORT:27017}"
      database: "${MONGODB_DATABASE:tcc-mongodb}"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: "${SERVER_PORT:8002}"
  error:
    include-stacktrace: ON_PARAM
