spring:
  application:
    name: api-checkout
  data:
    mongodb:
      host: host.docker.internal
      port: 27017
      database: tcc-mongodb

server:
  port: 8002
  error:
    include-stacktrace: ON_PARAM
