apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-api-cart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-api-cart-backend
  template:
    metadata:
      labels:
        app: tcc-api-cart-backend
    spec:
      containers:
        - name: backend
          image: ahmentz/tcc-backend:api-cart-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8001
          resources:
            requests:
              memory: "100Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8001
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8001
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:IdyfPnp3wp@tcc-db-mongodb:27017/tcc-mongodb?authSource=admin
            - name: SERVER_PORT
              value: "8001"
            - name: API_CATALOG_URL
              value: "http://api-catalog-backend-service:8000"
