apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-api-catalog-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-api-catalog-backend
  template:
    metadata:
      labels:
        app: tcc-api-catalog-backend
    spec:
      containers:
        - name: backend
          image: ahmentz/tcc-backend:api-catalog-latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 5
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:eZD04dIPHg@tcc-db-mongodb:27017/tcc-mongodb?authSource=admin
            - name: SERVER_PORT
              value: "8000"
            - name: API_CART_URL
              value: "http://api-catalog-backend-service:8001"
