spring:
  application:
    name: api-catalog
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tcc-mongodb

server:
  port: 8000
  error:
    include-stacktrace: ON_PARAM

app:
  api-cart-url: "http://localhost:8001"