spring:
  application:
    name: api-catalog
  data:
    mongodb:
      host: "${MONGODB_HOST:localhost}"
      port: "${MONGODB_PORT:27017}"
      database: "${MONGODB_DATABASE:tcc-mongodb}"

server:
  port: "${SERVER_PORT:8000}"
  error:
    include-stacktrace: ON_PARAM

app:
  api-cart-url: "${API_CART_URL:http://localhost:8001}"