spring:
  application:
    name: api-cart
  cloud:
    compatibility-verifier:
      enabled: false
  data:
    mongodb:
      host: localhost
      port: 27017
      database: tcc-mongodb

server:
  port: 8001
  error:
    include-stacktrace: ON_PARAM

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic