apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcc-api-cart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcc-api-cart-backend
  template:
    metadata:
      labels:
        app: tcc-api-cart-backend
    spec:
      containers:
        - name: backend
          image: ahmentz/tcc-backend:api-cart-latest
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "0.5"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://root:eZD04dIPHg@tcc-db-mongodb:27017/tcc-mongodb?authSource=admin
            - name: SERVER_PORT
              value: "8001"
            - name: API_CATALOG_URL
              value: "http://api-catalog-service:8000"
