name: backend-cart

on:
  push:
    branches: [ main ]
    paths:
      - 'api-cart/**'
      - '.github/workflows/backend-cart.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd api-cart
        ./mvnw clean verify

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: cart-api-build
        path: api-cart/target/*.jar
        retention-days: 5
