name: backend-checkout

on:
  push:
    branches: [ main ]
    paths:
      - 'api-checkout/**'
      - '.github/workflows/backend-checkout.yml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: |
        cd api-checkout
        chmod +x ./mvnw
        ./mvnw clean verify